import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Layout } from "@/components/layout/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ScrollArea } from "@/components/ui/scroll-area";
import { FileSearch, Info, Activity, Sparkles } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { cn } from "@/lib/utils";

// 1. Import the Context to get the stored data
import { useAnalysis } from "@/context/AnalysisContext";

// Initialize Gemini SDK
const genAI = new GoogleGenerativeAI(import.meta.env.VITE_GEMINI_API_KEY);

const ExplainabilityModule = () => {
  const navigate = useNavigate();

  // 2. Get Data directly from Global Context
  // We don't need to re-fetch because UploadXray already saved it here.
  const { previewUrl, heatmapData } = useAnalysis();

  const handleBackToUpload = () => navigate("/upload");

  // 3. Helper to convert image for Gemini
  async function urlToGenerativePart(url: string) {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        const result = reader.result as string;
        // Handle both Data URIs and Blob URLs
        const base64Data = result.includes(",") ? result.split(",")[1] : result;
        resolve({
          inlineData: { data: base64Data, mimeType: blob.type },
        });
      };
      reader.readAsDataURL(blob);
    });
  }

  // 4. Query for Gemini AI Medical Explanation
  const { data: aiExplanation, isLoading: isAiLoading } = useQuery({
    queryKey: ["geminiAnalysis", previewUrl], // Depend on previewUrl
    queryFn: async () => {
      if (!previewUrl) return null;
      const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
      
      // We send the ORIGINAL image to Gemini, but ask it to explain the Heatmap context
      const imagePart = await urlToGenerativePart(previewUrl);

      const prompt = `
        Act as an expert Radiologist and AI Explainer. 
        The patient is viewing their original X-ray alongside a Grad-CAM heatmap generated by a Vision Transformer model.
        
        Please provide a professional explanation:
        1. Explain that the highlighted areas in the heatmap show where the AI focused its attention to create the diagnostic report.
        2. Describe the clinical significance of these regions based on the anatomy (e.g., lungs, heart, or hilar regions).
        3. Add a disclaimer that this is an experimental tool to assist radiologists, not a final diagnosis.
        Format with clear headings and bullet points.
      `;

      const result = await model.generateContent([prompt, imagePart as any]);
      const response = await result.response;
      return response.text();
    },
    enabled: !!previewUrl,
  });

  return (
    <Layout>
      <div className="container mx-auto px-4 py-12 lg:py-20 min-h-[80vh]">
        {/* Header Section */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-4">
            <Sparkles className="w-4 h-4" /> AI Interpretability
          </div>
          <h1 className="text-3xl md:text-4xl font-bold mb-2">
            Explainability Module
          </h1>
          <p className="text-muted-foreground">
            Visualizing the "Why" behind AI-generated medical reports.
          </p>
        </div>

        {!previewUrl ? (
          <Card className="max-w-md mx-auto border-dashed">
            <CardContent className="flex flex-col items-center p-10">
              <FileSearch className="w-12 h-12 mb-4 text-muted-foreground opacity-50" />
              <p className="mb-6 text-center">
                No image data found. Please upload an X-ray to begin analysis.
              </p>
              <Button onClick={handleBackToUpload}>Return to Upload</Button>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-8">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
              
              {/* CARD 1: Original Image */}
              <Card className="overflow-hidden border-2">
                <CardHeader className="border-b bg-muted/30">
                  <CardTitle className="text-sm font-medium flex items-center gap-2">
                    <Activity className="w-4 h-4 text-primary" /> Original Scan
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-4 bg-black aspect-square flex items-center justify-center">
                  <img
                    src={previewUrl}
                    alt="Original X-ray"
                    className="max-h-full object-contain rounded-sm"
                  />
                </CardContent>
              </Card>

              {/* CARD 2: Backend Grad-CAM Heatmap */}
              <Card className="overflow-hidden border-2">
                <CardHeader className="border-b bg-muted/30">
                  <CardTitle className="text-sm font-medium flex items-center gap-2">
                    <Info className="w-4 h-4 text-primary" /> Grad-CAM Visualization
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-4 bg-black aspect-square flex items-center justify-center relative">
                  {/* DIRECTLY USE heatmapData FROM CONTEXT */}
                  {heatmapData ? (
                    <img
                      src={heatmapData}
                      alt="Heatmap"
                      className="max-h-full object-contain rounded-sm opacity-100 transition-opacity duration-700"
                    />
                  ) : (
                    <div className="text-white text-center text-sm opacity-70">
                      Heatmap data not found in context.
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* CARD 3: AI Narrative Result Section */}
              <Card className="lg:col-span-2 border-primary/20 shadow-lg overflow-hidden">
                <div className="h-1 bg-gradient-to-r from-primary via-blue-400 to-primary animate-pulse" />
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-primary" />
                    Automated Diagnostic Narrative
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  {isAiLoading ? (
                    <div className="space-y-3">
                      <Skeleton className="h-4 w-full" />
                      <Skeleton className="h-4 w-[90%]" />
                      <Skeleton className="h-4 w-[95%]" />
                      <Skeleton className="h-20 w-full" />
                    </div>
                  ) : (
                    <ScrollArea className="h-[300px] w-full pr-4">
                      <div className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap leading-relaxed">
                        {aiExplanation}
                      </div>
                    </ScrollArea>
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
};

export default ExplainabilityModule;